src/controllers/DocController.php
<?php
namespace wuyuxifeng\api\controllers;
use yii;  
use yii\helpers\Url;  
use yii\web\Response as BResponse;  
use wuyuxifeng\api\ApiPackage;
use wuyuxifeng\api\IApi;
use wuyuxifeng\api\ErrorHandler;
use wuyuxifeng\api\Response;
use wuyuxifeng\api\Config;
use wuyuxifeng\api\exception\InvalidApiException;

/**
 * 负责调用的控制器
 */
class DocController extends \yii\web\Controller{ 
    public $title;

   
	/**
	 * 注册异常捕获类，用于接管抛出的异常
	 *
	 * @return void
	 */
	function init(){
	    $this->layout="@wuyuxifeng/api/views/layouts/main";
    }

    /**
     * 模板渲染指定路径
     *
     * @param [type] $view
     * @param array $params
     * @return void
     */
    function render($view,$params=[]){
        return parent::render('@wuyuxifeng/api/views/doc/'.$view,$params);
    }

	/**
	 * invoke method
	 *
	 * @return void
	 */
	function actionIndex(){                
        $this->title('首页');
        return parent::render($this->module->overviewHtml);
    }
 
    function actionGroup(){       
 
        $list=Config::getActiveGroupList();
        
        $g=Yii::$app->request->get('g');  

     
        return $this->title($list['gname'].' 相关接口')->render('group',[
            'list'=>$list,
            'g'=>$g,
            'gname'=>$list['gname'],
            'count'=>count($list['list']),
            'v'=>$this->getNowv(),
        ]);
    }


    function actionInfo($view='info'){
        $info=Config::getMethodInfo();      
        $method=Yii::$app->request->get('method');  
        $g=Yii::$app->request->get('g');  
 
 
        return $this->title($method.'接口的详情')->render($view,[            
            'class'=>$info['class'],
            'method'=>$method,
            'apiUrl'=>Yii::$app->request->hostInfo .Url::to(['index/index','v'=>$this->getNowv(),'method'=>$method]),
            'v'=>$this->getNowv(),
            'gname'=>$info['gname'],
            'g'=>$g,
            'verbs'=>$info['class']->verbs,
        ]);
    }


    function actionTest(){  
        return $this->title('测试：'.$method)->actionInfo('test'); 
    } 
    function actionSearch(){
        $key=Yii::$app->request->get('key');
  
        $all=Yii::$app->controller->module->apiConfig;
 
        $list=Config::searchKey($key);

        return $this->title("搜索 $key")->render('search',[
            'v'=>$this->getNowv(),
            'list'=>$list,
            'key'=>$key,
        ]);
    }

    /**
     * 执行测试
     *
     * @return void
     */
    function actionDotest(){
        $data=$_REQUEST;     
        if($data['data']['token']){
            \setcookie('test_token',$data['data']['token'],time()+3600*24*30,'/');
        }
        $start = \microtime(true);
        $curl = curl_init(true);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        $reqUrl='';
        if(preg_match("/get/",strtolower($data['verbs']))){
            $url=http_build_query($data['data']);     
            $reqUrl=$data['apiurl'].'&'.$url;
            curl_setopt($curl, CURLOPT_URL,$reqUrl);
        }else{
            $reqUrl=$data['apiurl'];
            curl_setopt($curl, CURLOPT_URL,$data['apiurl']);
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data['data']);  
        } 
        $data = curl_exec($curl);
        $end = \microtime(true);
        // 检查是否有错误发生
        if(curl_errno($curl)){
            $return='curl error:'.curl_error($curl);     
            $return=[
                'code'=>'500',
                'msg'=>'curl error:'.curl_error($curl),
            ];       
        }else{
            $return=$data;
        }
        curl_close($curl);        
        return $this->asJson([
            'return'=>$return,
            'returnJson'=>is_array($return)?$return:json_decode($return),
            'time'=>round($end-$start,4),
            'reqUrl'=>$reqUrl
        ]);
 
    }


    /**
     * 设置title
     *
     * @param [type] $title
     * @return void
     */
    public function title($title){
        $this->title=$title;
        return $this;
    }
    /**
     * 获取当前的 版本号
     *
     * @return void
     */
    private function getNowv(){
        return Yii::$app->request->get('v',$this->module->defaultVersion);
    }
 
  
    function beforeAction($action){  
        if($this->module->openAccess===false && !$this->module->checkAccess($action)){
            throw new InvalidApiException('对不起，您现在还没获此操作的权限');
        }      
        return true;
    }
}

src/controllers/IndexController.php
<?php
namespace wuyuxifeng\api\controllers;
use yii;  
use yii\filters\auth\QueryParamAuth;  
use yii\filters\auth\CompositeAuth;  
use yii\filters\RateLimiter;
use wuyuxifeng\api\ApiPackage;
use wuyuxifeng\api\IApi;
use wuyuxifeng\api\ErrorHandler;
use wuyuxifeng\api\Response;
use wuyuxifeng\api\exception\InvalidApiException;

/**
 * 负责调用的控制器
 */
class IndexController extends \yii\base\Controller{ 
	static public $moduleIns=null;
	private $clazz;

	/**
	 * 注册异常捕获类，用于接管抛出的异常
	 *
	 * @return void
	 */
	function init(){		  
		$this->layout=false;	
		IndexController::$moduleIns=$this->module;		
		$handler=Yii::createObject($this->module->errorHandlerClass);	 
		$handler->register();	
		$method=Yii::$app->request->get('method',null);		 
		$v=Yii::$app->request->get('v',$this->module->defaultVersion);	 
		if($method===null){
			throw new InvalidApiException('请传入方法');
		}
		$apis=$this->module->apiConfig;
		if(!isset($apis[$v])){
			throw new InvalidApiException('版本号不存在');
		} 

		$methodArr=explode('.',$method);
		if(!isset($apis[$v][$method])){ 
			//接口模块级别查找
			$cate=$apis[$v][current($methodArr)];
			if(isset($cate['autoScanNamespace'])){
				$findClazz=array_slice($methodArr,1,count($methodArr));
				$findClazz[count($findClazz)-1]=\yii\helpers\Inflector::camelize(end($findClazz));
				$findClazz=$cate['autoScanNamespace'].'\\'.join('\\',$findClazz);
				if(class_exists($findClazz)){
                    $this->clazz=Yii::createObject($findClazz);
                    if(!$this->clazz instanceof IApi) throw new InvalidApiException('这不是一个IApi的实例');
                    return true;                    
                }  
			}			
			
			//模块配置查找
            if(empty($this->module->autoScanNamespace)) throw new InvalidApiException('找不到API:'.$method);
            $ms=$methodArr;
            $ms[count($ms)-1]=ucfirst(end($ms));
            $ms=join('\\',$ms);
            foreach($this->module->autoScanNamespace as $item){
                $path=$item.'\\'.$ms;
                if(class_exists($path)){
                    $this->clazz=Yii::createObject($path);
                    if(!$this->clazz instanceof IApi) throw new InvalidApiException('这不是一个IApi的实例');
                    return true;                    
                } 
            } 
			throw new InvalidApiException('找不到API:'.$method);
		}


		$classz=$apis[$v][$method];
		if(is_string($classz)){
			$classz=['class'=>$classz];
		}
		if(!class_exists($classz['class'])){
			throw new InvalidApiException('找不到class:'.$classz['class']);
		}

		$this->clazz=Yii::createObject($classz);
		if(! $this->clazz instanceof IApi){
			throw new InvalidApiException('这不是一个IApi的实例');
		}
		 
	}
 
	/**
	 * invoke method
	 *
	 * @return void
	 */
	function actionIndex(){ 	 
		$return=$this->clazz->prepareCheck(); 	 
		if($this->clazz->beforeHandle($this->clazz->attributes)){
			$return=$this->clazz->handle($this->clazz->attributes); 			
		}else{
			throw new InvalidApiException('强制终止运行');
		}
		$return=$this->clazz->afterHandle($return);	 
		echo $this->module->getResponse()->renderSuccess($return); 	 
		exit;
	} 

	/**
	 * 验证的行为,包含  回话的验证，速率的验证
	 *
	 * @return void
	 */
	public function behaviors()	{
		$behaviors = parent::behaviors();
		if($this->clazz->auth==true){ 		
	 
			$as=explode(',',$this->module->authType);	
			$authMethods=[];
			foreach($as as $i) {		
				$v=$this->module->builtInAuthTypes[$i];
				if(empty($v)) throw new InvalidApiException('无效的authType参数:'.$i);
				$authMethods[]=$v;
			}	
			$behaviors['auth'] = [
				'class'=>CompositeAuth::class,
				'authMethods'=>$authMethods
			];			
		}	
		return $behaviors;
	}
 
}

src/views/doc/group.php
<?php use yii\helpers\Url;?>
<ol class="breadcrumb">
  <li><i class='glyphicon glyphicon-home'></i> <a href="<?=\yii\helpers\Url::to(['doc/index'])?>">Overview</a></li>
  <li><a href=""><?=$v?></a></li>
  <li class="active"><?=Yii::$app->controller->title?> , 共计 <?=$count?> 个</li>
</ol>
 

<table class="table table-hover">
    <tr>
        <th>方法</th>
        <th>描述</th> 
        <th>支持动作</th> 
        <th>是否需要认证</th>
        <th>#</th>
    </tr>
    <?php foreach($list['list'] as $method=>$item):?>
    <tr>
        <td><a href="<?=\yii\helpers\Url::to(['info','method'=>$method,'v'=>$v,'g'=>$g])?>"><?=$method?></a></td>
        <td><?=$item['apiDescription']?></td>
        <td><?=$item['verbs']?></td>
        <td><?=$item['instance']['auth']?'<b style=color:red >true</b>':'false'?></td>
        <td>
            <a href="<?=Url::to(['doc/test','method'=>$method,'v'=>$v,'g'=>$g])?>">测试</a> |
            <a href="<?=Url::to(['doc/info','method'=>$method,'v'=>$v,'g'=>$g])?>#params">详细参数</a> |
            <a href="<?=Url::to(['doc/info','method'=>$method,'v'=>$v,'g'=>$g])?>#return">返回字段</a> |
            <a href="<?=Url::to(['doc/info','method'=>$method,'v'=>$v,'g'=>$g])?>#demo">示例结果</a>  
        </td>
    </tr>
    <?php endforeach?>
</table>

src/views/doc/index.php
 
<h1 class="page-header">接口文档概述</h1>


<ul class=ul > 
  <li>本文供前端开发工程师使用</li>
  <li>接口请求地址统一格式为: <?=\Yii::$app->request->hostInfo ?><?=\yii\helpers\Url::to(['index/index'])?>?v=v1&method=user.get 其中:
    <ul>
      <li><code>v</code>: 版本号，非必填，如：v1 ， 默认为<?=Yii::$app->controller->module->defaultVersion ?></li>
      <li><code>method</code>: 调用的接口名称，如:user.get</li>
    </ul>
  </li>
  <li>支持的请求动作有 <code>GET</code>/<code>POST</code>/<code>GET,POST</code> 等三种情况</li>
  <li>返回格式仅支持json格式,下面是几个完整的json示例: <br>
    <ul>
        <li><code>{"code":200,"msg":"success","data":null}</code></li>
        <li><code>{"code":500,"msg":"请传入xx字段","data":""}</code></li>
        <li><code>{"code":501,"msg":"登陆错误","data":""}</code></li>
        <li><code>{"code":200,"msg":"success","data":[]}</code></li>
        <li><code>{"code":200,"msg":"success","data":[{a:1,b:2},{a:3,b:4}]}</code></li>
    </ul>

    其中返回的字段：
    <ul>
      <li>code：整数，状态码。其中200表示成功（http协议状态码为200）；其他非200，如500，表示出现错误（http协议状态码为500）</li>
      <li>msg：字符串，返回的提示消息</li>
      <li>data：返回的具体数据</li>
    </ul>
 
  </li>

    <li>输入参数校验的类型 <a name=validate ></a>
        <ul>
            <li>required: 必填</li>
            <li>trim: 清空输出参数的前后空格</li>
            <li>number: 数字</li>
            <li>boolean: 布尔验证, 请传入 1或者0</li>
            <li>date: 日期格式</li>
            <li>email: 邮箱地址</li>
            <li>url: url地址</li>
            <li>ip: ip地址</li>
            <li>in: 范围内验证。 eg：in:1|2|3  表示输入的值必须是 1,2,3 其中的一个值 </li>
            <li>_xxxx: 带有下划线开头表示自定义验证</li>
        </ul>
    </li>
</ul>

 


<style>
.ul li{line-height:25px}
</style>

src/views/doc/info.php
<?php
$params=$class->params(); 
if($class->auth){
    $params['token']=[
        'field'=>'token',
        'type'=>'string',
        'validate'=>'required',
        'description'=>'登陆颁发的token',
    ];
}

list($refs,$codes,$marks)=$class->ref();
// ksort($params);
?>
<ol class="breadcrumb">
  <li><i class='glyphicon glyphicon-home'></i> <a href="<?=\yii\helpers\Url::to(['doc/index'])?>">Overview</a></li>
  <li><a href="#"><?=$v?></a></li>
  <li><a href="<?=\yii\helpers\Url::to(['doc/group','g'=>$g,'v'=>$v])?>"><?=$gname?></a></li>
  <li class="active"><?=$class->apiDescription?> <?=$method?></li>
</ol>



<h3>请求地址</h3>
<p class=apiurl ><label class="label label-warning"><?=$class->verbs?></label> <?=$apiUrl?> 
 
<a href="<?=\yii\helpers\Url::to(['doc/test','method'=>$method,'g'=>$g,'v'=>$v])?>" class='btn btn-success btn-xs'>测试工具>></a>

 
</p>

<?php if(!empty($marks)):?>
<h3>接口说明</h3>
<?=join(';',$marks)?>
<?php endif?>

<h3>输入参数</h3>
<table class="table table-striped table-bordered table-condensed">
    <tr>
        <th>字段</th>
        <th>数据类型</th>
        <th>验证条件 <a href="<?=\yii\helpers\Url::to(['doc/index'])?>#validate">？</a></th>
        <th>描述</th>
        <th style='width:30%'>示例值</th>
    </tr>
    
    <?php foreach($params as $field=>$val):?>    

    <tr class=tr-v >   
        <td><code><?=$field?></code></td>
        <td><?=$val['type']?:'string'?></td>
        <td>
        <?php           
            $sp='';
            if(is_string($val['validate'])){
                echo $sp.$val['validate'];
            }elseif(is_array($val['validate'])){
                foreach($val['validate'] as $k=>$v){         
                    if(is_numeric($k)) echo $sp.$v;
                    elseif(is_array($v)){
                        $title=json_encode($v,JSON_UNESCAPED_UNICODE);
                        echo $sp."<span title='$title'   >$k</span>";
                    }
                    $sp=',';
                }
            }
           
         ?>
        </td>
        <td><?=$val['description']?></td> 
        <td><?=$val['demo']?></td>
    </tr>
    <?php endforeach?>
</table>

<h3>返回字段</h3>
<table class="table table-striped table-bordered table-condensed" style='width:60%'>
    <tr>
        <th>字段</th>
        <th>返回类型</th>
        <th>说明</th>  
    </tr>    
    <?php foreach($refs as $k=>$val):?>
    <tr>   
        <td><code><?=$val['field']?></code></td>
        <td><?=$val['type']?></td>
        <td><?=$val['description']?></td>
    </tr>
    <?php endforeach?>
</table>

<?php if(!empty($codes)):?>
<h3>返回code</h3>
<table class="table table-striped table-bordered table-condensed" style='width:60%'>
    <tr>
        <th>code</th> 
        <th>说明</th>  
    </tr>    
    <?php foreach($codes as $k=>$val):?>
    <tr>   
        <td><code><?=$val['code']?></code></td>
        <td><?=$val['description']?></td> 
    </tr>
    <?php endforeach?>
</table>
<?php endif?>

<h3>返回结果示例JSON</h3>
<pre><code  id=well ><?=$class->returnJson()?></code></pre>
 
 
<style>
.tr-v span{text-decoration:underline}
table td {word-break: break-all;}
</style>
<script>
$(function(){
    var json=<?=$class->returnJson()?>; 
    var str = JSON.stringify(json, undefined, 2);
    document.getElementById('well').innerHTML = str; 

  
}) 
</script> 

src/views/doc/search.php
<?php use yii\helpers\Url;?>
<ol class="breadcrumb">
  <li><i class='glyphicon glyphicon-home'></i> <a href="<?=\yii\helpers\Url::to(['doc/index'])?>">Overview</a></li>
  <li class="active"><?=Yii::$app->controller->title?> , 相关接口 <?=$count?> 个</li>
</ol>
 

<table class="table table-hover">
    <tr>
        <th>方法</th>
        <th>版本</th>
        <th>描述</th> 
        <th>支持动作</th> 
        <th>是否需要认证</th>
        <th>#</th>
    </tr>
    <?php foreach($list as $item):?>
    <tr>
        <td><a href="<?=\yii\helpers\Url::to(['info','method'=>$item['method'],'v'=>$item['v'],'g'=>$item['g']])?>"><?=$item['method']?></a></td>
        <td><?=$item['v']?></td>
        <td><?=$item['apiDescription']?></td>
        <td><?=$item['verbs']?></td>
        <td><?=$item['auth']?'true':'false'?></td>
        <td>
            <a href="<?=Url::to(['doc/test','method'=>$item['method'],'v'=>$item['v'],'g'=>$item['g']])?>">测试</a> |
            <a href="<?=Url::to(['doc/info','method'=>$item['method'],'v'=>$item['v'],'g'=>$item['g']])?>#params">详细参数</a> |
            <a href="<?=Url::to(['doc/info','method'=>$item['method'],'v'=>$item['v'],'g'=>$item['g']])?>#return">返回字段</a> |
            <a href="<?=Url::to(['doc/info','method'=>$item['method'],'v'=>$item['v'],'g'=>$item['g']])?>#demo">示例结果</a>  
        </td>
    </tr>
    <?php endforeach?>
</table>

src/views/doc/test.php
<?php
$params=$class->params();
$validatestring=[];
foreach($params as $field=>$rule){ 
    foreach($rule['validate'] as $key=>$value)
        $validatestring[]=is_numeric($key)?$value:$key;
}
if($class->auth){
    $params['token']=[
        'field'=>'token',
        'type'=>'string',
        'validate'=>'required',
        'description'=>'登陆颁发的token',
    ];
}

$refs=$class->ref();

// ksort($params);
?>

<ol class="breadcrumb">
  <li><i class='glyphicon glyphicon-home'></i> <a href="<?=\yii\helpers\Url::to(['doc/index'])?>">Overview</a></li>
  <li><a href="#"><?=$v?></a></li>
  <li><a href="<?=\yii\helpers\Url::to(['doc/group','g'=>$g,'v'=>$v])?>"><?=$gname?></a></li>
  <li><a href="<?=\yii\helpers\Url::to(['doc/info','g'=>$g,'v'=>$v,'method'=>$method])?>"><?=$class->apiDescription?></a></li>
  <li class="active">测试 <?=$method?></li>
</ol>
 
<h3>请求地址</h3>
<p>
    <label class='label label-warning'><?=$class->verbs?></label>
    <span class="apiurl"><?=$apiUrl?></span>
</p> 

<?php if($refs['marks']):?>
<h3>备注说明</h3>
    <div class="alert alert-warning">
        <?php foreach($refs['marks'] as $item):?> 
        <p> <?=$item?></p>
        <?php endforeach?>
    </div>
<?php endif?>

<h3>输入参数</h3>
<table class="table table-striped table-bordered "  >
    <tr>
        <th style='width:100px'>字段</th>
        <th>输入值</th>
        <th>数据类型</th>
        <th>验证条件</th>
        <th style='width:300px'>描述</th>     
        <th style='width:200px'>示例值</th> 
    </tr>    
    <?php foreach($params as $field=>$val):?>
    <tr class='tr-field tr-v tr-<?=$field?>' >   
        <td class='field td-<?=$field?>' ><code><?=$field?></code></td>
        <td>
            <input type="text" style='width:100%' class=input >
        </td>
        <td><?=$val['type']?:'string'?></td>
        <td>       
        <?php           
            $sp='';
            if(is_string($val['validate'])){
                echo $sp.$val['validate'];
            }elseif(is_array($val['validate'])){
                foreach($val['validate'] as $k=>$v){         
                    if(is_numeric($k)) echo $sp.$v;
                    elseif(is_array($v)){
                        $title=json_encode($v,JSON_UNESCAPED_UNICODE);
                        echo $sp."<span title='$title'   >$k</span>";
                    }
                    $sp=',';
                }
            }
           
         ?>
        </td>
        <td><?=$val['description']?></td> 
        <td><?=$val['demo']?></td> 
    </tr>
    <?php endforeach?> 
</table> 

<button class='btn btn-success btnstart'>执行请求 </button> 
 
<h3 class=returnx >执行结果</h3>
<pre><code id="return">...</code></pre>

<div class=returnurl >
    <h3>访问的Url </h3>
    <div class="well well-returnurl">
        ...
    </div>
</div>

 
<script>
$(function(){
    if($('.tr-token').length>0 ){
        $('.tr-token .input').val('<?=$_COOKIE['test_token']?>')
    }

    $('.btnstart').click(function(){
        var btnobj=$(this);
        btnobj.attr('disabled',true).append('<i class="glyphicon glyphicon-refresh"></i>');
        var data={};
        var tokenObj=null;
        $('.tr-field').each(function(k,v){
            var field=$(v).find('.field').text();
            data[field]=$(v).find('.input').val();
            if(field=='token'){
                tokenObj=v;
            }
        });
       
        var apiurl=$('.apiurl').text(); 
        var method='<?=$method?>';
        var verbs='<?=$verbs?>';
        $('.returnx label').remove();   
  
        $.ajax({
            url:'<?=\yii\helpers\Url::to(["doc/dotest"])?>',
            type:'post',
            data:{
                data,apiurl,verbs        
            },
            success:function(ret){
                btnobj.attr('disabled',false).find('i').remove();
                $('.returnx label').remove();     
                $('.returnx').append('<label class="label label-warning" title="耗时">'+ret.time+'s </label>');
                $('#return').html('请求链接:<a href='+ret.reqUrl+' target=_blank > '+ret.reqUrl+'</a><br><br>'+ret.return);

            
                var str = JSON.stringify(ret.returnJson, undefined, 2);       
                $('#return').html(str);

                $('.well-returnurl').html("<a href='"+ret.reqUrl+"' target=_blank >"+ret.reqUrl+"</a>");
            },
            error:function(ret){
                btnobj.attr('disabled',false);
                console.log(ret)
                $('.returnx label').remove();     
                $('#return').html(ret.responseText); 
            }
        });
    })
});
</script>

<style>
.label{font-size:12px}
.tr-v span{text-decoration:underline}
table td {word-break: break-all;}
</style>

src/views/layouts/_css.php
<style>

/*
 * Base structure
 */

/* Move down content because we have a fixed navbar that is 50px tall */
body {
  padding-top: 50px;
}
 

/*
 * Global add-ons
 */

.sub-header {
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}

/*
 * Top navigation
 * Hide default border to remove 1px line.
 */
.navbar-fixed-top {
  border: 0;
}

/*
 * Sidebar
 */

/* Hide for mobile, show later */
.sidebar {
  display: none;
}
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 51px;
    bottom: 0;
    left: 0;
    z-index: 1000;
    display: block;
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
    background-color: #f5f5f5;
    border-right: 1px solid #eee;
  }
}

/* Sidebar navigation */
.nav-sidebar {
  margin-right: -21px; /* 20px padding + 1px border */
  margin-bottom: 20px;
  margin-left: -20px;
}
.nav-sidebar > li > a {
  padding-right: 20px;
  padding-left: 20px;
}
.nav-sidebar > .active > a,
.nav-sidebar > .active > a:hover,
.nav-sidebar > .active > a:focus {
  color: #fff;
  background-color: #428bca;
}


/*
 * Main content
 */

.main {
  padding: 20px;
}
@media (min-width: 768px) {
  .main {
    padding-right: 40px;
    padding-left: 40px;
  }
}
.main .page-header {
  margin-top: 0;
}


/*
 * Placeholder dashboard ideas
 */

.placeholders {
  margin-bottom: 30px;
  text-align: center;
}
.placeholders h4 {
  margin-bottom: 0;
}
.placeholder {
  margin-bottom: 20px;
}
.placeholder img {
  display: inline-block;
  border-radius: 50%;
}
h3x{color:#fff; background-color:#428bca;padding: 10px 5px; font-size:16px; font-weight:bold; }
h3{border-left:5px solid #00aeff; text-indent:10px;font-size:15px; font-weight:bold; color:#555}
</style>

src/views/layouts/main.php
 <?php 
 use yii\helpers\Url;  
 use wuyuxifeng\api\Config;  
$defaultVersion=Yii::$app->controller->module->defaultVersion;
$nowv=Yii::$app->request->get('v',$defaultVersion);
 
 
 ?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=docice-width, initial-scale=1">    
<title><?=(Yii::$app->controller->title) ?> - <?=Yii::$app->controller->module->docTitle?></title>
<link href="//cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
<script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>  
<?php $this->head() ?>
</head>
<?=$this->render('_css')?>
<?php $this->beginBody() ?>   
<body >
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?=Url::to(['doc/index'])?>">
            <?=Yii::$app->controller->module->docTitle?>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="https://gitee.com/wuyuxifeng/yii2-api" target=_blank >Help?</a></li>
 
            <li>  
                <select name="" id="vc" style='margin:15px 10px 0 20px' >
                    <?php foreach(Config::getAllVersions() as $v):?>                    
                        <option value="<?=$v?>" <?=$nowv==$v?'selected':''?> >版本： <?=$v?></option>
                    <?php endforeach?>
                </select>               
            </li>
 
          </ul>
          <form class="navbar-form navbar-right" action='<?=Url::to(['doc/search'])?>' method=get >
            <input type="text" class="form-control" placeholder="Search..." name=key >
          </form>
        </div>
      </div> 
    </nav>

<div class="container-fluid">    
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar navx"> 
                <li class="li-home"><a href="<?=Url::to(['doc/index','v'=>$nowv])?>">首页</a></li>
                <?php foreach(Config::getAllList() as $key=>$value):?>
                  <li class=li-<?=$key?> ><a href="<?=Url::to(['doc/group','g'=>$key,'v'=>$nowv])?>"><?=$value?></a></li>
                <?php endforeach?>
     
            </ul>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            
            <?=$content?>
        </div>

    </div>

</div>
<?php $this->endBody() ?>
<script>
$(function(){
    $('#vc').change(function(){
        var v=($(this).val());
        var url=window.location.href;    
        if(!/v=<?=$nowv?>/.test(url)){
            url=url+'?v='+v;   
        }else{
            url=url.replace(/v=<?=$nowv?>/,'v='+v)  ;   
        }
        location=url;
    });

    var g='<?=Yii::$app->request->get('g')?>';
    if(g!=''){
        $('.navx li').removeClass('active');
        $('.navx li.li-'+g).addClass('active');
    }else{
        $('.navx li.li-home').addClass('active');
    }
});
</script>
</body>
</html> 
<?php $this->endPage() ?> 
 